### ISSUE TITLE
Problem when try to install module, can't add module to IRIS

### ISSUE THREAD

**Issue by yahoopl** [socfortress/iris-wazuhindexer-module#4]
OS: clean Debian 12

sudo ./buildnpush2iris.sh -a
[BUILDnPUSH2IRIS] Pushing to Worker and App container!
[BUILDnPUSH2IRIS] Starting the build and push process..
./buildnpush2iris.sh: line 30: python3.9: command not found
ls: cannot access './dist': No such file or directory
[BUILDnPUSH2IRIS] Found latest module file:
[BUILDnPUSH2IRIS] Copy module file to worker container..
"docker cp" requires exactly 2 arguments.
See 'docker cp --help'.

Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH

Copy files/folders between a container and the local filesystem
[BUILDnPUSH2IRIS] Installing module in worker container..
ERROR: Directory 'dependencies/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
[BUILDnPUSH2IRIS] Restarting worker container..
iriswebapp_worker
[BUILDnPUSH2IRIS] Copy module file to app container..
"docker cp" requires exactly 2 arguments.
See 'docker cp --help'.

Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH

Copy files/folders between a container and the local filesystem
[BUILDnPUSH2IRIS] Installing module in app container..
ERROR: Directory 'dependencies/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
[BUILDnPUSH2IRIS] Restarting app container..
iriswebapp_app
[BUILDnPUSH2IRIS] Completed!

**Comment by tkolaski** [comment]
Same problem on Debian 12

**Comment by shaker402** [comment]
dear [tkolaski](https://github.com/tkolaski), how do you fix the above

**Comment by X40c** [comment]
If you use this ommand `docker exec -it iriswebapp_worker /bin/sh` and issue the command `pip install --upgrade pip` that will solve the pip issue. I'm struggling as to what the `./.dist`  directory is and what files it should contain. It needs the `setup.py` file and the `pyproject.toml` but other than that IDK

**Comment by shaker402** [comment]
thank you for your help , the integration done successfully ,  but i can not searching task , I had the following error  in Dim Task:
Task ID:
97cb0817-a10c-4a36-b773-303e29ed64c5
Task finished on:
2024-03-15 00:59:52.192154
Module name:
iris_wazuhindexer_module
Hook name:
on_manual_trigger_ioc
User:
administrator
Case ID:
1
Success:
Failure
Logs
Traceback (most recent call last): File "/iriswebapp/app/iris_engine/module_handler/module_handler.py", line 478, in task_hook_wrapper task_status = mod_inst.hooks_handler(hook_name, hook_ui_name, data=_obj) File "/opt/venv/lib/python3.9/site-packages/iris_wazuhindexer_module/IrisWazuhindexerInterface.py", line 95, in hooks_handler case = CaseDetailsSchema().dump(data) File "/opt/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 549, in dump result = self._serialize(processed_obj, many=many) File "/opt/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 517, in _serialize value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute) File "/opt/venv/lib/python3.9/site-packages/marshmallow/fields.py", line 340, in serialize return self._serialize(value, attr, obj, **kwargs) File "/opt/venv/lib/python3.9/site-packages/marshmallow/fields.py", line 1981, in _serialize return self._serialize_method(obj) File "/iriswebapp/app/schema/marshables.py", line 2255, in get_status_name return CaseStatus(obj.status_id).name AttributeError: 'list' object has no attribute 'status_id' 


could you help me to fix it

**Comment by shaker402** [comment]
![image](https://github.com/socfortress/iris-wazuhindexer-module/assets/49626160/6c1117ae-2935-43a2-8183-3047f4579702)
